name: Playwright Login Tests
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username for login'
        required: false
        default: ''
      password:
        description: 'Password for login'
        required: false
        default: ''

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        PLAYWRIGHT_USERNAME: ${{ github.event.inputs.username || '' }}
        PLAYWRIGHT_PASSWORD: ${{ github.event.inputs.password || '' }}
      run: npx playwright test
