name: Factorial Clocker
on:
  workflow_dispatch:
    inputs:
      accountData:
        description: 'Account data JSON string'
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup account-data.json
      run: echo '${{ github.event.inputs.accountData }}' > account-data.json
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
